### ISSUE TITLE
Does this work on mixed partition images?

### ISSUE THREAD

**Issue by withgallantry** [resin-io/node-ext2fs#22]
I'm trying to open a mixed partition image. One is Fat16 and one is Ext3. When trying to open the image I get the following error:
{ Error: , Unknown error: -2133571347 errno: -2133571347, code: '' }

For info, it was a raspberry pi image. I'm trying to access the Ext3 partition to change configuration files.

**Comment by zvin** [comment]
Hello @withgallantry 
This module works with raw partitions.
If you have a disk image with multiple partitions, you need to read the partition table first to get the ext partition offset and use node-ext2fs with a disk image wrapper that knows this offset.

This module can do it for you: https://github.com/resin-io-modules/resin-image-fs , it uses partitioninfo and node-ext2fs internally.

```javascript
const Bluebird = require('bluebird')
const imagefs = require('resin-image-fs')
const process = require('process')

// The partition number is the partition number as it would be on Linux: /dev/sdx3
const partitionNumber = 3

Bluebird.using(imagefs.interact('/path/to/the/disk/image', partitionNumber), (fs) => {
    // fs is an object like node's fs
    fs.createReadStream('/some/file', 'r').pipe(process.stdout)
})
```

**Comment by lurch** [comment]
On most Raspberry Pi images, the Ext3 partition is the second one, i.e. `const partitionNumber = 2`
